### ISSUE TITLE
javautil_pheno

### ISSUE THREAD

**Issue by visze** [Phenomics/annotation-simulation#1]
@drseb where can I get it?

I get the error:
```
Exception in thread "main" java.lang.NoSuchMethodError: ontologizer.go.OBOParser.getDataVersion()Ljava/lang/String;
	at hpo.HpoDataProvider.parseOntology(HpoDataProvider.java:254)
	at hpo.HpoDataProvider.parseOntologyAndAssociations(HpoDataProvider.java:183)
	at drseb.AnnotationSimulator.<init>(AnnotationSimulator.java:42)
	at de.charite.compbio.exomiserbenchmark.Main.initialize(Main.java:117)
	at de.charite.compbio.exomiserbenchmark.Main.main(Main.java:94)
```

I think I do not use the latest version of javautil_pheno

**Comment by iamkoehler** [comment]
Look at the pom.xml

**Comment by visze** [comment]
ah ok. I did not recognize it because I have ontologizer installed. is the ontologizer here http://compbio.charite.de/tl_files/maven the same as here: https://github.com/drseb/ontologizer?

**Comment by iamkoehler** [comment]
Yes

**Comment by visze** [comment]
I used you github ontologizer because the ontologizer repo at compbio is invalid. e.g. the parent etc is missing. I get the rror if I use only the compbio repo (removing my internal repo completely)
```
Failed to execute goal on project annotation-simulation: Could not resolve dependencies for project annotation-simulation:annotation-simulation:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at ontologizer:ontologizer:jar:0.0.2-SNAPSHOT: Failed to read artifact descriptor for ontologizer:ontologizer:jar:0.0.2-SNAPSHOT: Could not find artifact ontologizer:ontologizer.parent:pom:0.0.2-SNAPSHOT in compbio (http://compbio.charite.de/tl_files/maven) -> [Help 1]

```

**Comment by visze** [comment]
ok the problem is different. exomiser uses ontologizer 0.1 but benchmark not 0.2-snapshot. The problem is that the method `ontologizer.go.OBOParser.getDataVersion()` is not present in v0.1 therefore it fails..

**Comment by visze** [comment]
@drseb can you give me access to your javautil_pheno code for debuging?

**Comment by iamkoehler** [comment]
exomiser uses 0.0.1 . we should update to 0.0.2

**Comment by iamkoehler** [comment]
you should be able to git clone this repo and do a mvn install. is this working?

**Comment by visze** [comment]
can you paste the javautil_pheno git url? E.g. https://github.com/drseb/javautil_pheno.git is wrong :-(

P.S.: Yes I mean 0.0.1 and 0.0.2 :-) too many zeros...

**Comment by iamkoehler** [comment]
you don't need the source. you need

```
<dependency>
    <groupId>ontologizer</groupId>
    <artifactId>ontologizer</artifactId>
    <version>0.0.2-SNAPSHOT</version>
  </dependency>
    <dependency>
    <groupId>javautil_pheno</groupId>
    <artifactId>javautil_pheno</artifactId>
    <version>0.0.2-SNAPSHOT</version>
  </dependency>
```

from 

```
<repositories>
        <repository>
            <id>compbio</id>
            <url>http://compbio.charite.de/tl_files/maven</url>
        </repository>
    </repositories>
```

**Comment by visze** [comment]
jep. but after fixing the ontologizer bug I get the error:

```
Exception in thread "main" java.lang.NoSuchMethodError: hpo.DiseaseEntry.<init>(Lhpo/DiseaseId;Lutil/OntologyHelper;)V
	at util.OntologyUtil.parseAnnotationFileHpoFormat(OntologyUtil.java:261)
	at util.OntologyUtil.parseOntologyAnnotations(OntologyUtil.java:147)
	at hpo.HpoDataProvider.parseAssociations(HpoDataProvider.java:473)
	at hpo.HpoDataProvider.parseOntologyAndAssociations(HpoDataProvider.java:189)
	at drseb.AnnotationSimulator.<init>(AnnotationSimulator.java:42)
	at de.charite.compbio.exomiserbenchmark.Main.initialize(Main.java:115)
	at de.charite.compbio.exomiserbenchmark.Main.main(Main.java:92)
```

To figure out what happens I need the class hpo.DiseaseEntry and I guess it comes from javautil_pheno

**Comment by iamkoehler** [comment]
Make a new project and put into the pom.xml:

```
<repositories>
        <repository>
            <id>compbio</id>
            <url>http://compbio.charite.de/tl_files/maven</url>
        </repository>
    </repositories>
    
<dependencies>
 
  <dependency>
    <groupId>ontologizer</groupId>
    <artifactId>ontologizer</artifactId>
    <version>0.0.2-SNAPSHOT</version>
  </dependency>
    <dependency>
    <groupId>javautil_pheno</groupId>
    <artifactId>javautil_pheno</artifactId>
    <version>0.0.2-SNAPSHOT</version>
  </dependency>
  <dependency>
    <groupId>annotation-simulation</groupId>
    <artifactId>annotation-simulation</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </dependency>
</dependencies>

 <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

Does this work?
